---
- name: uninstall all things
  hosts: all
  tasks: 
    - name: unistall java maven git jenkins
      apt:
        name: "{{item}}"
        state: absent
        purge: yes
      with_items: 
        - openjdk-*
        - maven
        - git
        - jenkins/jenkins
...
