---
pkg1: tomcat10
pkg2: tomcat10-admin
state1: present
cache1: yes
cache2: no
file1: tomcat-users.xml
dest1: /etc/tomcat10
port1: 8080
port2: 9090
path1: /etc/tomcat10/server.xml
state2: restarted
seconds: 30
server1: "http://172.31.21.2:9090"
server2: "http://172.31.17.30:9090"
status: 200
...
